package com.example.speechpath;

/**
 * Represents the response returned by the speech assessment backend.
 *
 * Data flow:
 * Android → Spring Boot → FastAPI → Android
 *
 * The backend returns:
 * - transcript: what the speech model understood
 * - expected: the phrase the user was supposed to say
 * - score: similarity score from 0 to 100
 */
public class ScoreResponse {

    // Transcription generated by the speech recognition model
    private String transcript;

    // Phrase that the user was expected to pronounce
    private String expected;

    // Word-level similarity score (0-100)
    private int score;

    /**
     * Empty constructor required by Gson/Retrofit
     * to create this object from the JSON response.
     */
    public ScoreResponse() {
    }

    public String getTranscript() {
        return transcript;
    }

    public void setTranscript(String transcript) {
        this.transcript = transcript;
    }

    public String getExpected() {
        return expected;
    }

    public void setExpected(String expected) {
        this.expected = expected;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }
}
